const AUTH = {
    NOME_USUARIO_INCORRETO: "Nome de usuário incorreto.",
    SENHA_INCORRETA: "Senha incorreta",
    SENHA_INVALIDA: "A senha deve ser composta de 6 a 20 caracteres.",
    ERRO_AO_LOGAR: "Ocorreu um erro ao realizar seu login. Tente novamente.",
    FORBIDDEN: "Você não possui permissão para acessar esse recurso.",
};

const ESTABELECIMENTO = {
    ESTABELECIMENTO_NAO_ENCONTRADO: "Estabelecimento não encontrado.",
    ID_INVALIDO: "O ID do Estabelecimento é inválido.",
    BUSCA_ESTABELECIMENTO: "Não foi possível encontrar o Estabelecimento.",
    BUSCA_ESTABELECIMENTOS: "Não foi possível encontrar os Estabelecimentos.",
    SALVAMENTO_ESTABELECIMENTO: "Não foi possível salvar o Estabelecimento.",
    ATUALIZACAO_ESTABELECIMENTO: "Não foi possível atualizar o Estabelecimento.",
    EXCLUSAO_ESTABELECIMENTO: "Não foi possível deletar o Estabelecimento.",
    TEMPO_MINIMO_ENTREGA_OBRIGATORIO: "O tempo mínimo da entrega é obrigatório.",
    TEMPO_MAXIMO_ENTREGA_OBRIGATORIO: "O tempo máximo da entrega é obrigatório.",
    INICIO_HORARIO_FUNCIONAMENTO_OBRIGATORIO: "O início do horário de funcionamento é obrigatório.",
    INICIO_HORARIO_FUNCIONAMENTO_INVALIDO: "O início do horário de funcionamento é inválido.",
    FIM_HORARIO_FUNCIONAMENTO_OBRIGATORIO: "O fim do horário de funcionamento é obrigatório.",
    FIM_HORARIO_FUNCIONAMENTO_INVALIDO: "O fim do horário de funcionamento é inválido.",
    NOME_SUBSECAO_TAMANHO_MINIMO: "O nome da subseção do Cardápio deve ter no mínimo 3 caracteres.",
    NOME_SUBSECAO_TAMANHO_MAXIMO: "O nome da subseção do Cardápio deve ter no máximo 30 caracteres.",
    NOME_SUBSECAO_OBRIGATORIO: "O nome da subseção do Cardápio é obrigatório.",
    NOME_SECAO_TAMANHO_MINIMO: "O nome da seção do Cardápio deve ter no mínimo 3 caracteres.",
    NOME_SECAO_TAMANHO_MAXIMO: "O nome da seção do Cardápio deve ter no máximo 30 caracteres.",
    NOME_SECAO_OBRIGATORIO: "O nome da seção do Cardápio é obrigatório.",
    NOME_TAMANHO_MINIMO: "O nome do Estabelecimento deve ter no mínimo 3 caracteres.",
    NOME_TAMANHO_MAXIMO: "O nome do Estabelecimento deve ter no máximo 50 caracteres.",
    NOME_OBRIGATORIO: "O nome do Estabelecimento é obrigatório.",
    CATEGORIA_INVALIDA: "A categoria ({VALUE}) do Estabelecimento é inválida.",
    CATEGORIA_OBRIGATORIA: "O Estabelecimento deve possuir ao menos uma categoria.",
    FORMA_PAGAMENTO_INVALIDA: "A forma de pagamento ({VALUE}) do Estabelecimento é inválida.",
    FORMA_PAGAMENTO_OBRIGATORIA: "O Estabelecimento deve possuir ao menos uma forma de pagamento.",
    TELEFONE_INVALIDO: "O número de telefone ({VALUE}) do Estabelecimento é inválido.",
    TELEFONE_OBRIGATORIO: "O Estabelecimento deve possuir ao menos um telefone.",
    VALOR_ENTREGA_OBRIGATORIO: "O valor da entrega é obrigatório.",
    TEMPO_ENTREGA_OBRIGATORIO: "O tempo mínimo e máximo da entrega são obrigatórios.",
    HORARIO_FUNCIONAMENTO_OBRIGATORIO: "O horário de funcionamento do Estabelecimento é obrigatório.",
    AVALIACAO_MINIMA: "A avaliação mínima para o Estabelecimento é 1.",
    AVALIACAO_MAXIMA: "A avaliação máxima para o Estabelecimento é 5.",
};

const GESTOR = {
    GESTOR_NAO_ENCONTRADO: "Gestor não encontrado.",
    ID_INVALIDO: "O ID do Gestor é inválido.",
    BUSCA_GESTOR: "Não foi possível encontrar o Gestor.",
    BUSCA_GESTORES: "Não foi possível encontrar os Gestores.",
    SALVAMENTO_GESTOR: "Não foi possível salvar o Gestor.",
    ATUALIZACAO_GESTOR: "Não foi possível atualizar o Gestor.",
    EXCLUSAO_GESTOR: "Não foi possível deletar o Gestor.",
    NOME_USUARIO_TAMANHO_MINIMO: "O nome de usuário do Gestor deve ter no mínimo 3 caracteres.",
    NOME_USUARIO_TAMANHO_MAXIMO: "O nome de usuário do Gestor deve ter no máximo 30 caracteres.",
    NOME_USUARIO_OBRIGATORIO: "O nome de usuário do Gestor é obrigatório.",
    SENHA_OBRIGATORIA: "A senha do Gestor é obrigatória.",
    PERMISSAO_OBRIGATORIA: "O Gestor deve possuir uma permissão.",
    PERMISSAO_INVALIDA: "A permissão ({VALUE}) é inválida.",
};

const PEDIDO = {
    PEDIDO_NAO_ENCONTRADO: "Pedido não encontrado.",
    ID_INVALIDO: "O ID do Pedido é inválido.",
    BUSCA_PEDIDO: "Não foi possível encontrar o Pedido.",
    BUSCA_PEDIDOS: "Não foi possível encontrar os Pedidos.",
    SALVAMENTO_PEDIDO: "Não foi possível salvar o Pedido.",
    ATUALIZACAO_PEDIDO: "Não foi possível atualizar o Pedido.",
    EXCLUSAO_PEDIDO: "Não foi possível deletar o Pedido.",
    VALOR_TOTA_INVALIDO: "O valor total do Pedido não pode ser negativo.",
    VALOR_TOTAL_OBRIGATORIO: "O valor total do Pedido é obrigatório.",
    VALOR_ENTREGA_INVALIDO: "O valor da entrega do Pedido não pode ser negativo.",
    VALOR_ENTREGA_OBRIGATORIO: "O valor da entrega do Pedido é obrigatório.",
    FORMA_PAGAMENTO_INVALIDA: "A forma de pagamento ({VALUE}) do Pedido é inválida.",
    FORMA_PAGAMENTO_OBRIGATORIA: "A forma de pagamento do Pedido é obrigatória.",
    TROCO_INVALIDO: "O troco do Pedido não pode ser negativo.",
    AVALIACAO_MINIMA: "A avaliação mínima para o Pedido é 1.",
    AVALIACAO_MAXIMA: "A avaliação máxima para o Pedido é 5.",
    STATUS_INVALIDO: "O status ({VALUE}) do Pedido é inválido.",
    STATUS_OBRIGATORIO: "O status do Pedido é obrigatório.",
    PEDIDO_VINCULACAO_ESTABELECIMENTO_OBRIGATORIA: "O Pedido deve pertencer a um Estabelecimento.",
    PEDIDO_VINCULACAO_USUARIO_OBRIGATORIA: "O Pedido deve pertencer a um Usuário.",
    ITENS_OBRIGATORIOS: "O Pedido deve possuir pelo menos um item.",
    PRECO_ITEM_INVALIDO: "O preço de um item do Pedido não pode ser negativo.",
    PRECO_ITEM_OBRIGATORIO: "O preço de um item do Pedido é obrigatório.",
    QUANTIDADE_MINIMA_ITEM: "A quantidade mínima de um item do Pedido é 1.",
    QUANTIDADE_ITEM_OBRIGATÓRIA: "A quantidade de um item do Pedido é obrigatória.",
    ITEM_VINCULACAO_PRODUTO_OBRIGATORIA: "Um item do Pedido deve ser vinculado a um Produto.",
    OBSERVACAO_ITEM_TAMANHO_MAXIMO: "O tamanho máximo da observação de um item de um Pedido é 150.",
};

const PRODUTO = {
    PRODUTO_NAO_ENCONTRADO: "Produto não encontrado.",
    ID_INVALIDO: "O ID do Produto é inválido.",
    BUSCA_PRODUTO: "Não foi possível encontrar o Produto.",
    BUSCA_PRODUTOS: "Não foi possível encontrar os Produtos.",
    SALVAMENTO_PRODUTO: "Não foi possível salvar o Produto.",
    ATUALIZACAO_PRODUTO: "Não foi possível atualizar o Produto.",
    EXCLUSAO_PRODUTO: "Não foi possível deletar o Produto.",
    NOME_TAMANHO_MINIMO: "O nome do Produto deve ter no mínimo 3 caracteres.",
    NOME_TAMANHO_MAXIMO: "O nome do Produto deve ter no máximo 30 caracteres.",
    NOME_OBRIGATORIO: "O nome do Produto é obrigatório.",
    PRECO_OBRIGATORIO: "O preço do Produto é obrigatório.",
    PRECO_INVALIDO: "O preço do Produto não pode ser negativo.",
    DESCRICAO_TAMANHO_MAXIMO: "A descrição do Produto deve ter no máximo 150 caracteres.",
    TAMANHO_MAXIMO: "O tamanho do Produto deve ter no máximo 20 caracteres.",
    VINCULACAO_ESTABELECIMENTO_OBRIGATORIA: "O Produto deve pertencer a um Estabelecimento.",
};

const USUARIO = {
    USUARIO_NAO_ENCONTRADO: "Usuário não encontrado.",
    ID_INVALIDO: "O ID do Usuário é inválido.",
    BUSCA_USUARIO: "Não foi possível encontrar o Usuário.",
    BUSCA_USUARIOS: "Não foi possível encontrar os Usuários.",
    SALVAMENTO_USUARIO: "Não foi possível salvar o Usuário.",
    ATUALIZACAO_USUARIO: "Não foi possível atualizar o Usuário.",
    EXCLUSAO_USUARIO: "Não foi possível deletar o Usuário.",
    EMAIL_OBRIGATORIO: "O e-mail do Usuário é obrigatório.",
    EMAIL_INVALIDO: "O e-mail ({VALUE}) é inválido.",
    ROLE_OBRIGATORIO: "O papel do Usuário é obrigatório.",
    ROLE_INVALIDO: "O papel ({VALUE}) é inválido.",
    NOME_USUARIO_TAMANHO_MINIMO: "O nome de usuário do Usuário deve ter no mínimo 3 caracteres.",
    NOME_USUARIO_TAMANHO_MAXIMO: "O nome de usuário do Usuário deve ter no máximo 30 caracteres.",
    NOME_USUARIO_OBRIGATORIO: "O nome de usuário é obrigatório.",
    SENHA_OBRIGATORIA: "A senha do Usuário é obrigatória.",
    NOME_COMPLETO_TAMANHO_MINIMO: "O nome completo do Usuário deve ter no mínimo 5 caracteres.",
    NOME_COMPLETO_TAMANHO_MAXIMO: "O nome completo do Usuário deve ter no máximo 50 caracteres.",
    NOME_COMPLETO_OBRIGATORIO: "O nome completo do Usuário é obrigatório.",
    CPF_OBRIGATORIO: "O CPF do Usuário é obrigatório.",
    CPF_INVALIDO: "O CPF ({VALUE}) é inválido.",
    TELEFONE_OBRIGATORIO: "O telefone do Usuário é obrigatório.",
    TELEFONE_INVALIDO: "O número de telefone ({VALUE}) do Usuário é inválido.",
    PERMISSAO_OBRIGATORIA: "O Vendedor deve possuir uma permissão.",
    PERMISSAO_INVALIDA: "A permissão ({VALUE}) é inválida.",
    VINCULACAO_ESTABELECIMENTO_OBRIGATORIA: "O Vendedor deve pertencer a um Estabelecimento.",
};

const MensagensErro = Object.freeze({
    AUTH,
    ESTABELECIMENTO,
    GESTOR,
    PRODUTO,
    PEDIDO,
    USUARIO,
});

export default MensagensErro;