apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: 'mongo'
  replicas: 1
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-primary
          image: mongo
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: myclaim
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 2Gi