apiVersion: v1
kind: Service
metadata:
  name: usuario-service
  labels:
    name: usuario-service
spec:
  type: NodePort
  selector:
    app: usuario-service
  ports:
    - port: 8083
      targetPort: 8083