apiVersion: v1
kind: Service
metadata:
  name: usuario-service
  labels:
    name: usuario-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
  clusterIP: None
  selector:
    role: usuario-service