apiVersion: apps/v1
kind: Deployment
metadata:
  name: qconveniente-api
  labels:
    app: qconveniente
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qconveniente
      tier: api
  template:
    metadata:
      labels:
        app: qconveniente
        tier: api
    spec:
      containers:
        - name: api
          image: qconveniente-api:v1.5.3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: 'mongodb://mongo:27017/app'
            - name: REDIS_HOST
              value: 'redis'
            - name: ESTABELECIMENTO_SERVICE_URL
              value: 'http://estabelecimento-service:8083/'
            - name: PEDIDO_SERVICE_URL
              value: 'http://pedido-service:8083/'
            - name: USUARIO_SERVICE_URL
              value: 'http://usuario-service:8083/'