apiVersion: v1
kind: Service
metadata:
  name: pedido-service
  labels:
    name: pedido-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  clusterIP: None
  selector:
    role: pedido-service