apiVersion: v1
kind: Service
metadata:
  name: pedido-service
  labels:
    name: pedido-service
spec:
  type: NodePort
  selector:
    app: pedido-service
  ports:
    - port: 8082
      targetPort: 8082